### PR TITLE
Fixed GFCard issue by adding image as optional parameter.

### PR DESCRIPTION
**Pull request by shubhamkatore**

### CODE REVIEW

**Comment by shubhamkatore** [comment]
@Sandipkakadiya @deepikahr Please take a look at it.

**Comment by Sandipkakadiya** [comment]
> @Sandipkakadiya @deepikahr Please take a look at it.

Which ana

> @Sandipkakadiya @deepikahr Please take a look at it.

Which analysis_options.yaml did you remove? @shubhamkatore. Was it really necessary?

**Comment by Sandipkakadiya** [comment]
> > @Sandipkakadiya @deepikahr Please take a look at it.
> 
> Which ana
> 
> > @Sandipkakadiya @deepikahr Please take a look at it.
> 
> Which one analysis_options.yaml did you remove? @shubhamkatore. Was it really necessary?

**Comment by shubhamkatore** [comment]
> > > @Sandipkakadiya @deepikahr Please take a look at it.
> > 
> > 
> > Which one analysis_options.yaml did you remove? @shubhamkatore. Was it really necessary?

@Sandipkakadiya I have removed avoid_as, build was failing due to this line https://travis-ci.com/github/ionicfirebaseapp/getwidget/builds/228080197

**Pull request merged**
